### ISSUE TITLE
Failed to start image acquisition

### ISSUE THREAD

**Issue by max-seeger** [vvvv/VL.Devices.IDS#6]
We are trying to use an IDS uEye+ camera (U3-3680XCP-NIR Rev.1.2), but get the following error: 

Failed to start image acquisition
System.ApplicationException: Error-Code: 11 (PEAK_RETURN_CODE_NOT_FOUND) | Error-Description: There is no node with the given name (AcquisitionFrameRateMinFunc)!
   at peak.core.NodeMap.FindNodeFloat(String name)
   at peak.core.NodeMap.FindNode[NodeType](String name)
   at VL.Devices.IDS.Acquisition.Start(VideoIn videoIn, DeviceDescriptor deviceDescriptor, ILogger logger, Int2 resolution, Int32 fps, IConfiguration configuration)
   at VL.Devices.IDS.VideoIn.VL.Lib.Basics.Video.IVideoSource2.Start(VideoPlaybackContext ctx)
   
   
I already tried different versions of IDS Peak (2.8, 2.11, 2.12). The same camera is working in the IDS Peak Cockpit and VL.Devices.IDS is working flawlessly with other older uEye cameras, I had here for testing.

**Comment by joreg** [comment]
we don't have that particular camera at hand for testing, but i found something in the code that could make a difference. please test with latest nuget version 1.0.2 and report back.

**Comment by max-seeger** [comment]
Thanks for the quick help @joreg !
I just tried it out and it didn't fix it, but the error message has changed:

Failed to start image acquisition
System.ApplicationException: Error-Code: 11 (PEAK_RETURN_CODE_NOT_FOUND) | Error-Description: There is no node with the given name (WidthMinReg)!
   at peak.core.NodeMap.FindNodeInteger(String name)
   at peak.core.NodeMap.FindNode[NodeType](String name)
   at VL.Devices.IDS.Acquisition.Start(VideoIn videoIn, DeviceDescriptor deviceDescriptor, ILogger logger, Int2 resolution, Int32 fps, IConfiguration configuration)
   at VL.Devices.IDS.VideoIn.VL.Lib.Basics.Video.IVideoSource2.Start(VideoPlaybackContext ctx)
   
If this would be any help, we could also drop off the test device we have here at your office?

**Comment by joreg** [comment]
ok please try nuget 1.0.3 with another small change. if that doesn't take us a step further, having the device at hand would help.

**Comment by max-seeger** [comment]
There's a new Out of Range exception that seems to be  solvable:

"Failed to start image acquisition
System.ApplicationException: Error-Code: 12 (PEAK_RETURN_CODE_OUT_OF_RANGE) | Error-Description: The difference between Value = 640 and Min = 48 must be dividable without rest by Inc = 12. : OutOfRangeException thrown in node 'Width' while calling 'Width.SetValue()' (file 
'IntegerT.h', line 81)
   at peak.core.nodes.IntegerNode.SetValue(Int64 value)
   at VL.Devices.IDS.Acquisition.Start(VideoIn videoIn, DeviceDescriptor deviceDescriptor, ILogger logger, Int2 resolution, Int32 fps, IConfiguration configuration)
   at VL.Devices.IDS.VideoIn.VL.Lib.Basics.Video.IVideoSource2.Start(VideoPlaybackContext ctx)"
   
   
   If this this isn't the last error to solve I can bring by the camera later this week. Thanks a lot for your help!

**Comment by joreg** [comment]
ok this error is just a hint that you need to specify the resolution in that given increment. latest pack now also returns the increment info on the info output.
